# Getting comfortable with Python 

Let's do all the types! (well, not *all* of them)

# Importing NumPy

It is customary to import NumPy as `np`:

In [3]:
import numpy as np

As you will cover in homework one, the `np.array` is the key data structure in numpy for dense arrays of data.

(More precisely, the type is `np.ndarray`, but we use `np.array` to construct them.)

NumPy `array`s have 2 main properties you need to keep in mind:

1. Shape
2. Data type (or `dtype`) of the data they contain

In particular, a NumPy `array` can only contain data of a single type (more nuance on this later).

# Creating Arrays

<span style="color:red; font-weight: bold;">What is `x1`'s `shape` and `dtype`?</span>

In [12]:
x1 = np.array([[1., 2.], [3., 4.]])

In [13]:
x1

array([[1., 2.],
       [3., 4.]])

In [14]:
x1.shape

(2, 2)

In [15]:
x1.dtype

dtype('float64')

<span style="color:red; font-weight: bold;">What is `x2`'s `shape` and `dtype`?</span>

In [8]:
x2 = np.array([x for x in range(5)])

In [11]:
x2

array([0, 1, 2, 3, 4])

In [9]:
x2.shape

(5,)

In [10]:
x2.dtype

dtype('int64')

Array's don't have to contain numbers:

<span style="color:red; font-weight: bold;">What is `x3`'s `shape` and `dtype`?</span>

In [4]:
x3 = np.array([["A", "matrix"], ["of", "words."]])

In [5]:
x3.shape

(2, 2)

In [6]:
x3.dtype

dtype('<U6')

## Making Arrays of Zeros

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

## Making Arrays of Ones

In [18]:
np.ones([3, 2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## Making an 'identity matrix'

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Getting Diagonals

Confusingly, `np.diag` serves two purposes:

In [30]:
np.arange(4)

array([0, 1, 2, 3])

In [31]:
np.diag(np.arange(4))

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3]])

In [32]:
np.diag(np.diag(np.arange(4)))

array([0, 1, 2, 3])

## Making Arrays from ranges:

The `np.arange(start, stop, step)` function is like the python `range` function.

In [ ]:
np.arange(0, 10, 2)

You can make a range of other types as well:

## Interpolating numbers 

The `linspace(start,end,num)` function generates `num` numbers evenly spaced between the `start` and `end`.

In [ ]:
np.linspace(0, 5, 10)

Learn more about working with [datetime objects](https://docs.scipy.org/doc/numpy/reference/arrays.datetime.html#).


# Properties of Arrays

## Shape

Arrays have a shape which corresponds to the number of rows, columns, fibers, ...

In [34]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)
arr.shape

[[1. 2. 3.]
 [4. 5. 6.]]


(2, 3)

## Type

Arrays have a type which corresponds to the type of data they contain

In [35]:
arr.dtype

dtype('float64')

In [36]:
np.arange(1, 5).dtype

dtype('int64')

In [37]:
(np.array([True, False])).dtype

dtype('bool')

In [38]:
np.array(["Hello", "Worlddddd!"]).dtype

dtype('<U10')

What does `<U6` mean?

- `<` Little Endian
- `U` Unicode
- `6` length of longest string

#### and we can change the type of an array:

In [40]:
np.array([1, 2, 3]).astype(float)

array([1., 2., 3.])

In [41]:
np.array(["1", "2", "3"]).astype(int)

array([1, 2, 3])

Learn more about numpy [array types](https://docs.scipy.org/doc/numpy/user/basics.types.html)


# Jagged Arrays

Is the following valid?

```python
arr = np.array([[1, 2, 3], [4, 5], [6]])
```

In [42]:
arr = np.array([[1, 2, 3], [4, 5], [6]])
arr

array([list([1, 2, 3]), list([4, 5]), list([6])], dtype=object)

What happened? 

### Issues with Jagged Arrays

 <img src="http://csharpcorner.mindcrackerinc.netdna-cdn.com/UploadFile/955025/C-Sharp-interview-question-part2/Images/jagged%20array.png">

### Jagged arrays can be problematic:

1. Difficult to index (extract columns).
```python
arr[0,1] 
 > Error
arr[0][1] 
 > 2
```
1. Not as efficiently represented in contiguous memory.

# Reshaping

Often you will need to reshape matrices.  Suppose you have the following array:

In [43]:
np.arange(1, 13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

<span style="color:red; font-weight:bold;">What will the following produce:</span>

```python
np.arange(1, 13).reshape(4,3)
```

**Option A:**

```python
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])
```

**Option B:**

```python
array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])
```

**Solution**

In [53]:
np.arange(1, 13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Flattening Matrix

Flattening a matrix (higher dimensional array) produces a one dimensional array.

In [51]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [55]:
arr.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Checking equality

In [56]:
arr.flatten() == arr.reshape(-1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

# Review

We covered a lot of concepts, but make sure you know what each of these do:

* `type`
* `np.array`
* `np.arange`
* `np.linspace`

Where `x` is an `ndarray`:

* `x.dtype`
* `x.shape`
* `x.flatten`
* `x.reshape`

<span style="color:red; font-weight:bold;">As an exercise for yourself, write a one-sentence description of what each one does. This will help you retain information better!</span>